package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Almacenmaterial generated by hbm2java
 */
@Entity
@Table(name = "almacenmaterial"
      , catalog = "bdalmacen")
public class Almacenmaterial implements java.io.Serializable
{

   private Integer idalmacenmaterial;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idalmacen;
   private Integer idmaterial;
   private Integer idestado;

   public Almacenmaterial()
   {
   }

   public Almacenmaterial(String fecharegistro, String fechamodificacion, Integer idalmacen, Integer idmaterial, Integer idestado)
   {
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idalmacen = idalmacen;
      this.idmaterial = idmaterial;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idalmacenmaterial", unique = true, nullable = false)
   public Integer getIdalmacenmaterial()
   {
      return this.idalmacenmaterial;
   }

   public void setIdalmacenmaterial(Integer idalmacenmaterial)
   {
      this.idalmacenmaterial = idalmacenmaterial;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idalmacen")
   public Integer getIdalmacen()
   {
      return this.idalmacen;
   }

   public void setIdalmacen(Integer idalmacen)
   {
      this.idalmacen = idalmacen;
   }

   @Column(name = "idmaterial")
   public Integer getIdmaterial()
   {
      return this.idmaterial;
   }

   public void setIdmaterial(Integer idmaterial)
   {
      this.idmaterial = idmaterial;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
