package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "cargo"
      , catalog = "bdalmacen")
public class Cargo implements java.io.Serializable
{

   private Integer idcargo;
   private String cargo;
   private String descripcion;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idestado;

   public Cargo()
   {
   }

   public Cargo(String cargo, String descripcion, String fecharegistro, String fechamodificacion)
   {
      this.cargo = cargo;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
   }

   public Cargo(String cargo, String descripcion, String fecharegistro, String fechamodificacion, Integer idestado)
   {
      this.cargo = cargo;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idcargo", unique = true, nullable = false)
   public Integer getIdcargo()
   {
      return this.idcargo;
   }

   public void setIdcargo(Integer idcargo)
   {
      this.idcargo = idcargo;
   }

   @Column(name = "cargo", nullable = false, length = 20)
   public String getCargo()
   {
      return this.cargo;
   }

   public void setCargo(String cargo)
   {
      this.cargo = cargo;
   }

   @Column(name = "descripcion", nullable = false, length = 250)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "fecharegistro", nullable = false, length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", nullable = false, length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
