package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria"
      , catalog = "bdalmacen")
public class Categoria implements java.io.Serializable
{

   private Integer idcategoria;
   private String categoria;
   private String codigocategoria;
   private String descripcion;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idestado;

   public Categoria()
   {
   }

   public Categoria(String categoria, String codigocategoria, String descripcion, String fecharegistro, String fechamodificacion, Integer idestado)
   {
      this.categoria = categoria;
      this.codigocategoria = codigocategoria;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idcategoria", unique = true, nullable = false)
   public Integer getIdcategoria()
   {
      return this.idcategoria;
   }

   public void setIdcategoria(Integer idcategoria)
   {
      this.idcategoria = idcategoria;
   }

   @Column(name = "categoria", length = 50)
   public String getCategoria()
   {
      return this.categoria;
   }

   public void setCategoria(String categoria)
   {
      this.categoria = categoria;
   }

   @Column(name = "codigocategoria", length = 50)
   public String getCodigocategoria()
   {
      return this.codigocategoria;
   }

   public void setCodigocategoria(String codigocategoria)
   {
      this.codigocategoria = codigocategoria;
   }

   @Column(name = "descripcion", length = 250)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
