package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categoriaenlace generated by hbm2java
 */
@Entity
@Table(name = "categoriaenlace"
      , catalog = "bdalmacen")
public class Categoriaenlace implements java.io.Serializable
{

   private Integer idcategoriaenlace;
   private String categoriaenlace;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idestado;

   public Categoriaenlace()
   {
   }

   public Categoriaenlace(String categoriaenlace)
   {
      this.categoriaenlace = categoriaenlace;
   }

   public Categoriaenlace(String categoriaenlace, String fecharegistro, String fechamodificacion, Integer idestado)
   {
      this.categoriaenlace = categoriaenlace;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idcategoriaenlace", unique = true, nullable = false)
   public Integer getIdcategoriaenlace()
   {
      return this.idcategoriaenlace;
   }

   public void setIdcategoriaenlace(Integer idcategoriaenlace)
   {
      this.idcategoriaenlace = idcategoriaenlace;
   }

   @Column(name = "categoriaenlace", nullable = false, length = 50)
   public String getCategoriaenlace()
   {
      return this.categoriaenlace;
   }

   public void setCategoriaenlace(String categoriaenlace)
   {
      this.categoriaenlace = categoriaenlace;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
