package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Centro generated by hbm2java
 */
@Entity
@Table(name = "centro"
      , catalog = "bdalmacen")
public class Centro implements java.io.Serializable
{

   private Integer idcentro;
   private String centro;
   private String descripcion;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idestado;

   public Centro()
   {
   }

   public Centro(String centro, String descripcion, String fecharegistro, String fechamodificacion)
   {
      this.centro = centro;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
   }

   public Centro(String centro, String descripcion, String fecharegistro, String fechamodificacion, Integer idestado)
   {
      this.centro = centro;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idcentro", unique = true, nullable = false)
   public Integer getIdcentro()
   {
      return this.idcentro;
   }

   public void setIdcentro(Integer idcentro)
   {
      this.idcentro = idcentro;
   }

   @Column(name = "centro", nullable = false, length = 50)
   public String getCentro()
   {
      return this.centro;
   }

   public void setCentro(String centro)
   {
      this.centro = centro;
   }

   @Column(name = "descripcion", nullable = false, length = 250)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "fecharegistro", nullable = false, length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", nullable = false, length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
