package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Detallesolicitud generated by hbm2java
 */
@Entity
@Table(name = "detallesolicitud"
      , catalog = "bdalmacen")
public class Detallesolicitud implements java.io.Serializable
{

   private Integer iddetallesolicitud;
   private Integer cantidad;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idsolicitud;
   private Integer idestado;
   private Integer idusuario;

   public Detallesolicitud()
   {
   }

   public Detallesolicitud(Integer cantidad, String fecharegistro, String fechamodificacion, Integer idsolicitud, Integer idestado, Integer idusuario)
   {
      this.cantidad = cantidad;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idsolicitud = idsolicitud;
      this.idestado = idestado;
      this.idusuario = idusuario;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "iddetallesolicitud", unique = true, nullable = false)
   public Integer getIddetallesolicitud()
   {
      return this.iddetallesolicitud;
   }

   public void setIddetallesolicitud(Integer iddetallesolicitud)
   {
      this.iddetallesolicitud = iddetallesolicitud;
   }

   @Column(name = "cantidad")
   public Integer getCantidad()
   {
      return this.cantidad;
   }

   public void setCantidad(Integer cantidad)
   {
      this.cantidad = cantidad;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idsolicitud")
   public Integer getIdsolicitud()
   {
      return this.idsolicitud;
   }

   public void setIdsolicitud(Integer idsolicitud)
   {
      this.idsolicitud = idsolicitud;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

   @Column(name = "idusuario")
   public Integer getIdusuario()
   {
      return this.idusuario;
   }

   public void setIdusuario(Integer idusuario)
   {
      this.idusuario = idusuario;
   }

}
