package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Detallekardex generated by hbm2java
 */
@Entity
@Table(name = "detallekardex"
      , catalog = "bdalmacen")
public class Detallekardex implements java.io.Serializable
{

   private Integer iddetallekardex;
   private String fechavencimiento;
   private Float preciounitario;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idkardex;
   private Integer idestado;

   public Detallekardex()
   {
   }

   public Detallekardex(String fechavencimiento, Float preciounitario, String fecharegistro, String fechamodificacion, Integer idkardex, Integer idestado)
   {
      this.fechavencimiento = fechavencimiento;
      this.preciounitario = preciounitario;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idkardex = idkardex;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "iddetallekardex", unique = true, nullable = false)
   public Integer getIddetallekardex()
   {
      return this.iddetallekardex;
   }

   public void setIddetallekardex(Integer iddetallekardex)
   {
      this.iddetallekardex = iddetallekardex;
   }

   @Column(name = "fechavencimiento", length = 20)
   public String getFechavencimiento()
   {
      return this.fechavencimiento;
   }

   public void setFechavencimiento(String fechavencimiento)
   {
      this.fechavencimiento = fechavencimiento;
   }

   @Column(name = "preciounitario", precision = 12, scale = 0)
   public Float getPreciounitario()
   {
      return this.preciounitario;
   }

   public void setPreciounitario(Float preciounitario)
   {
      this.preciounitario = preciounitario;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idkardex")
   public Integer getIdkardex()
   {
      return this.idkardex;
   }

   public void setIdkardex(Integer idkardex)
   {
      this.idkardex = idkardex;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
