package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Egreso generated by hbm2java
 */
@Entity
@Table(name = "egreso"
      , catalog = "bdalmacen")
public class Egreso implements java.io.Serializable
{

   private Integer idegreso;
   private Integer cantidad;
   private Float preciounitario;
   private Float preciototal;
   private String fechaingreso;
   private String fecharegistro;
   private String fechamodificacion;
   private String observacion;
   private Integer idkardex;
   private Integer iddetallesolicitud;
   private Integer idestado;
   private Integer idusuario;
   private Integer idtipomovimiento;

   public Egreso()
   {
   }

   public Egreso(Integer cantidad, Float preciounitario, Float preciototal, String fechaingreso, String fecharegistro, String fechamodificacion, String observacion, Integer idkardex, Integer iddetallesolicitud, Integer idestado, Integer idusuario, Integer idtipomovimiento)
   {
      this.cantidad = cantidad;
      this.preciounitario = preciounitario;
      this.preciototal = preciototal;
      this.fechaingreso = fechaingreso;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.observacion = observacion;
      this.idkardex = idkardex;
      this.iddetallesolicitud = iddetallesolicitud;
      this.idestado = idestado;
      this.idusuario = idusuario;
      this.idtipomovimiento = idtipomovimiento;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idegreso", unique = true, nullable = false)
   public Integer getIdegreso()
   {
      return this.idegreso;
   }

   public void setIdegreso(Integer idegreso)
   {
      this.idegreso = idegreso;
   }

   @Column(name = "cantidad")
   public Integer getCantidad()
   {
      return this.cantidad;
   }

   public void setCantidad(Integer cantidad)
   {
      this.cantidad = cantidad;
   }

   @Column(name = "preciounitario", precision = 12, scale = 0)
   public Float getPreciounitario()
   {
      return this.preciounitario;
   }

   public void setPreciounitario(Float preciounitario)
   {
      this.preciounitario = preciounitario;
   }

   @Column(name = "preciototal", precision = 12, scale = 0)
   public Float getPreciototal()
   {
      return this.preciototal;
   }

   public void setPreciototal(Float preciototal)
   {
      this.preciototal = preciototal;
   }

   @Column(name = "fechaingreso", length = 20)
   public String getFechaingreso()
   {
      return this.fechaingreso;
   }

   public void setFechaingreso(String fechaingreso)
   {
      this.fechaingreso = fechaingreso;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "observacion", length = 250)
   public String getObservacion()
   {
      return this.observacion;
   }

   public void setObservacion(String observacion)
   {
      this.observacion = observacion;
   }

   @Column(name = "idkardex")
   public Integer getIdkardex()
   {
      return this.idkardex;
   }

   public void setIdkardex(Integer idkardex)
   {
      this.idkardex = idkardex;
   }

   @Column(name = "iddetallesolicitud")
   public Integer getIddetallesolicitud()
   {
      return this.iddetallesolicitud;
   }

   public void setIddetallesolicitud(Integer iddetallesolicitud)
   {
      this.iddetallesolicitud = iddetallesolicitud;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

   @Column(name = "idusuario")
   public Integer getIdusuario()
   {
      return this.idusuario;
   }

   public void setIdusuario(Integer idusuario)
   {
      this.idusuario = idusuario;
   }

   @Column(name = "idtipomovimiento")
   public Integer getIdtipomovimiento()
   {
      return this.idtipomovimiento;
   }

   public void setIdtipomovimiento(Integer idtipomovimiento)
   {
      this.idtipomovimiento = idtipomovimiento;
   }

}
