package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Enlace generated by hbm2java
 */
@Entity
@Table(name = "enlace"
      , catalog = "bdalmacen")
public class Enlace implements java.io.Serializable
{

   private Integer idenlace;
   private String enlace;
   private String descripcion;
   private Integer orden;
   private String rutaenlace;
   private String imagen;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer ididcategoriaenlace;

   public Enlace()
   {
   }

   public Enlace(String enlace, String descripcion, String rutaenlace, String imagen, String fecharegistro, String fechamodificacion)
   {
      this.enlace = enlace;
      this.descripcion = descripcion;
      this.rutaenlace = rutaenlace;
      this.imagen = imagen;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
   }

   public Enlace(String enlace, String descripcion, Integer orden, String rutaenlace, String imagen, String fecharegistro, String fechamodificacion, Integer ididcategoriaenlace)
   {
      this.enlace = enlace;
      this.descripcion = descripcion;
      this.orden = orden;
      this.rutaenlace = rutaenlace;
      this.imagen = imagen;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.ididcategoriaenlace = ididcategoriaenlace;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idenlace", unique = true, nullable = false)
   public Integer getIdenlace()
   {
      return this.idenlace;
   }

   public void setIdenlace(Integer idenlace)
   {
      this.idenlace = idenlace;
   }

   @Column(name = "enlace", nullable = false, length = 50)
   public String getEnlace()
   {
      return this.enlace;
   }

   public void setEnlace(String enlace)
   {
      this.enlace = enlace;
   }

   @Column(name = "descripcion", nullable = false, length = 250)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "orden")
   public Integer getOrden()
   {
      return this.orden;
   }

   public void setOrden(Integer orden)
   {
      this.orden = orden;
   }

   @Column(name = "rutaenlace", nullable = false, length = 50)
   public String getRutaenlace()
   {
      return this.rutaenlace;
   }

   public void setRutaenlace(String rutaenlace)
   {
      this.rutaenlace = rutaenlace;
   }

   @Column(name = "imagen", nullable = false, length = 50)
   public String getImagen()
   {
      return this.imagen;
   }

   public void setImagen(String imagen)
   {
      this.imagen = imagen;
   }

   @Column(name = "fecharegistro", nullable = false, length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", nullable = false, length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "ididcategoriaenlace")
   public Integer getIdidcategoriaenlace()
   {
      return this.ididcategoriaenlace;
   }

   public void setIdidcategoriaenlace(Integer ididcategoriaenlace)
   {
      this.ididcategoriaenlace = ididcategoriaenlace;
   }

}
