package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado"
      , catalog = "bdalmacen")
public class Estado implements java.io.Serializable
{

   private Integer idestado;
   private String estado;

   public Estado()
   {
   }

   public Estado(String estado)
   {
      this.estado = estado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idestado", unique = true, nullable = false)
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

   @Column(name = "estado", nullable = false, length = 50)
   public String getEstado()
   {
      return this.estado;
   }

   public void setEstado(String estado)
   {
      this.estado = estado;
   }

}
