package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona"
      , catalog = "bdalmacen")
public class Persona implements java.io.Serializable
{

   private Integer idpersona;
   private String nombrepersona;
   private String apellidopaterno;
   private String apellidomaterno;
   private String ci;
   private String fechanacimiento;
   private String fecharegistro;
   private String fechamodificacion;
   private String correo;
   private String telefono;
   private Integer idestado;
   private Integer idreparticion;
   private Integer idsexo;
   private Integer idcargo;

   public Persona()
   {
   }

   public Persona(String nombrepersona, String apellidopaterno, String apellidomaterno, String ci, String fechanacimiento, String fecharegistro, String fechamodificacion, String correo, String telefono)
   {
      this.nombrepersona = nombrepersona;
      this.apellidopaterno = apellidopaterno;
      this.apellidomaterno = apellidomaterno;
      this.ci = ci;
      this.fechanacimiento = fechanacimiento;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.correo = correo;
      this.telefono = telefono;
   }

   public Persona(String nombrepersona, String apellidopaterno, String apellidomaterno, String ci, String fechanacimiento, String fecharegistro, String fechamodificacion, String correo, String telefono, Integer idestado, Integer idreparticion, Integer idsexo, Integer idcargo)
   {
      this.nombrepersona = nombrepersona;
      this.apellidopaterno = apellidopaterno;
      this.apellidomaterno = apellidomaterno;
      this.ci = ci;
      this.fechanacimiento = fechanacimiento;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.correo = correo;
      this.telefono = telefono;
      this.idestado = idestado;
      this.idreparticion = idreparticion;
      this.idsexo = idsexo;
      this.idcargo = idcargo;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idpersona", unique = true, nullable = false)
   public Integer getIdpersona()
   {
      return this.idpersona;
   }

   public void setIdpersona(Integer idpersona)
   {
      this.idpersona = idpersona;
   }

   @Column(name = "nombrepersona", nullable = false, length = 50)
   public String getNombrepersona()
   {
      return this.nombrepersona;
   }

   public void setNombrepersona(String nombrepersona)
   {
      this.nombrepersona = nombrepersona;
   }

   @Column(name = "apellidopaterno", nullable = false, length = 50)
   public String getApellidopaterno()
   {
      return this.apellidopaterno;
   }

   public void setApellidopaterno(String apellidopaterno)
   {
      this.apellidopaterno = apellidopaterno;
   }

   @Column(name = "apellidomaterno", nullable = false, length = 50)
   public String getApellidomaterno()
   {
      return this.apellidomaterno;
   }

   public void setApellidomaterno(String apellidomaterno)
   {
      this.apellidomaterno = apellidomaterno;
   }

   @Column(name = "ci", nullable = false, length = 30)
   public String getCi()
   {
      return this.ci;
   }

   public void setCi(String ci)
   {
      this.ci = ci;
   }

   @Column(name = "fechanacimiento", nullable = false, length = 20)
   public String getFechanacimiento()
   {
      return this.fechanacimiento;
   }

   public void setFechanacimiento(String fechanacimiento)
   {
      this.fechanacimiento = fechanacimiento;
   }

   @Column(name = "fecharegistro", nullable = false, length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", nullable = false, length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "correo", nullable = false, length = 50)
   public String getCorreo()
   {
      return this.correo;
   }

   public void setCorreo(String correo)
   {
      this.correo = correo;
   }

   @Column(name = "telefono", nullable = false, length = 50)
   public String getTelefono()
   {
      return this.telefono;
   }

   public void setTelefono(String telefono)
   {
      this.telefono = telefono;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

   @Column(name = "idreparticion")
   public Integer getIdreparticion()
   {
      return this.idreparticion;
   }

   public void setIdreparticion(Integer idreparticion)
   {
      this.idreparticion = idreparticion;
   }

   @Column(name = "idsexo")
   public Integer getIdsexo()
   {
      return this.idsexo;
   }

   public void setIdsexo(Integer idsexo)
   {
      this.idsexo = idsexo;
   }

   @Column(name = "idcargo")
   public Integer getIdcargo()
   {
      return this.idcargo;
   }

   public void setIdcargo(Integer idcargo)
   {
      this.idcargo = idcargo;
   }

}
