package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor"
      , catalog = "bdalmacen")
public class Proveedor implements java.io.Serializable
{

   private Integer idproveedor;
   private String proveedor;
   private String responsable;
   private String telefono;
   private String email;
   private String direccion;
   private String razonsocial;
   private String fecharegistro;
   private String fechamodificacion;
   private String observacion;
   private Integer idestado;

   public Proveedor()
   {
   }

   public Proveedor(String proveedor, String responsable, String telefono, String email, String direccion, String razonsocial, String fecharegistro, String fechamodificacion, String observacion, Integer idestado)
   {
      this.proveedor = proveedor;
      this.responsable = responsable;
      this.telefono = telefono;
      this.email = email;
      this.direccion = direccion;
      this.razonsocial = razonsocial;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.observacion = observacion;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idproveedor", unique = true, nullable = false)
   public Integer getIdproveedor()
   {
      return this.idproveedor;
   }

   public void setIdproveedor(Integer idproveedor)
   {
      this.idproveedor = idproveedor;
   }

   @Column(name = "proveedor", length = 100)
   public String getProveedor()
   {
      return this.proveedor;
   }

   public void setProveedor(String proveedor)
   {
      this.proveedor = proveedor;
   }

   @Column(name = "responsable", length = 100)
   public String getResponsable()
   {
      return this.responsable;
   }

   public void setResponsable(String responsable)
   {
      this.responsable = responsable;
   }

   @Column(name = "telefono", length = 30)
   public String getTelefono()
   {
      return this.telefono;
   }

   public void setTelefono(String telefono)
   {
      this.telefono = telefono;
   }

   @Column(name = "email", length = 60)
   public String getEmail()
   {
      return this.email;
   }

   public void setEmail(String email)
   {
      this.email = email;
   }

   @Column(name = "direccion", length = 250)
   public String getDireccion()
   {
      return this.direccion;
   }

   public void setDireccion(String direccion)
   {
      this.direccion = direccion;
   }

   @Column(name = "razonsocial", length = 70)
   public String getRazonsocial()
   {
      return this.razonsocial;
   }

   public void setRazonsocial(String razonsocial)
   {
      this.razonsocial = razonsocial;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "observacion", length = 250)
   public String getObservacion()
   {
      return this.observacion;
   }

   public void setObservacion(String observacion)
   {
      this.observacion = observacion;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
