package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reparticion generated by hbm2java
 */
@Entity
@Table(name = "reparticion"
      , catalog = "bdalmacen")
public class Reparticion implements java.io.Serializable
{

   private Integer idreparticion;
   private String reparticion;
   private String descripcion;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idarea;
   private Integer idestado;

   public Reparticion()
   {
   }

   public Reparticion(String reparticion, String descripcion, String fecharegistro, String fechamodificacion)
   {
      this.reparticion = reparticion;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
   }

   public Reparticion(String reparticion, String descripcion, String fecharegistro, String fechamodificacion, Integer idarea, Integer idestado)
   {
      this.reparticion = reparticion;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idarea = idarea;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idreparticion", unique = true, nullable = false)
   public Integer getIdreparticion()
   {
      return this.idreparticion;
   }

   public void setIdreparticion(Integer idreparticion)
   {
      this.idreparticion = idreparticion;
   }

   @Column(name = "reparticion", nullable = false, length = 50)
   public String getReparticion()
   {
      return this.reparticion;
   }

   public void setReparticion(String reparticion)
   {
      this.reparticion = reparticion;
   }

   @Column(name = "descripcion", nullable = false, length = 100)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "fecharegistro", nullable = false, length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", nullable = false, length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idarea")
   public Integer getIdarea()
   {
      return this.idarea;
   }

   public void setIdarea(Integer idarea)
   {
      this.idarea = idarea;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
