package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol"
      , catalog = "bdalmacen")
public class Rol implements java.io.Serializable
{

   private Integer idrol;
   private String rol;
   private String descripcion;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idestado;

   public Rol()
   {
   }

   public Rol(String rol, String descripcion, String fecharegistro, String fechamodificacion)
   {
      this.rol = rol;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
   }

   public Rol(String rol, String descripcion, String fecharegistro, String fechamodificacion, Integer idestado)
   {
      this.rol = rol;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idrol", unique = true, nullable = false)
   public Integer getIdrol()
   {
      return this.idrol;
   }

   public void setIdrol(Integer idrol)
   {
      this.idrol = idrol;
   }

   @Column(name = "rol", nullable = false, length = 50)
   public String getRol()
   {
      return this.rol;
   }

   public void setRol(String rol)
   {
      this.rol = rol;
   }

   @Column(name = "descripcion", nullable = false, length = 250)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "fecharegistro", nullable = false, length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", nullable = false, length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
