package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name = "sexo"
      , catalog = "bdalmacen")
public class Sexo implements java.io.Serializable
{

   private Integer idsexo;
   private String sexo;

   public Sexo()
   {
   }

   public Sexo(String sexo)
   {
      this.sexo = sexo;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idsexo", unique = true, nullable = false)
   public Integer getIdsexo()
   {
      return this.idsexo;
   }

   public void setIdsexo(Integer idsexo)
   {
      this.idsexo = idsexo;
   }

   @Column(name = "sexo", nullable = false, length = 1)
   public String getSexo()
   {
      return this.sexo;
   }

   public void setSexo(String sexo)
   {
      this.sexo = sexo;
   }

}
