package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "solicitud"
      , catalog = "bdalmacen")
public class Solicitud implements java.io.Serializable
{

   private Integer idsolicitud;
   private String solicitud;
   private String codigosolicitud;
   private String fechasolicitud;
   private String observacion;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer gestion;
   private Integer idtiposolicitud;
   private Integer idestado;
   private Integer idusuario;

   public Solicitud()
   {
   }

   public Solicitud(String solicitud)
   {
      this.solicitud = solicitud;
   }

   public Solicitud(String solicitud, String codigosolicitud, String fechasolicitud, String observacion, String fecharegistro, String fechamodificacion, Integer gestion, Integer idtiposolicitud, Integer idestado, Integer idusuario)
   {
      this.solicitud = solicitud;
      this.codigosolicitud = codigosolicitud;
      this.fechasolicitud = fechasolicitud;
      this.observacion = observacion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.gestion = gestion;
      this.idtiposolicitud = idtiposolicitud;
      this.idestado = idestado;
      this.idusuario = idusuario;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idsolicitud", unique = true, nullable = false)
   public Integer getIdsolicitud()
   {
      return this.idsolicitud;
   }

   public void setIdsolicitud(Integer idsolicitud)
   {
      this.idsolicitud = idsolicitud;
   }

   @Column(name = "solicitud", nullable = false, length = 100)
   public String getSolicitud()
   {
      return this.solicitud;
   }

   public void setSolicitud(String solicitud)
   {
      this.solicitud = solicitud;
   }

   @Column(name = "codigosolicitud", length = 30)
   public String getCodigosolicitud()
   {
      return this.codigosolicitud;
   }

   public void setCodigosolicitud(String codigosolicitud)
   {
      this.codigosolicitud = codigosolicitud;
   }

   @Column(name = "fechasolicitud", length = 10)
   public String getFechasolicitud()
   {
      return this.fechasolicitud;
   }

   public void setFechasolicitud(String fechasolicitud)
   {
      this.fechasolicitud = fechasolicitud;
   }

   @Column(name = "observacion", length = 250)
   public String getObservacion()
   {
      return this.observacion;
   }

   public void setObservacion(String observacion)
   {
      this.observacion = observacion;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "gestion")
   public Integer getGestion()
   {
      return this.gestion;
   }

   public void setGestion(Integer gestion)
   {
      this.gestion = gestion;
   }

   @Column(name = "idtiposolicitud")
   public Integer getIdtiposolicitud()
   {
      return this.idtiposolicitud;
   }

   public void setIdtiposolicitud(Integer idtiposolicitud)
   {
      this.idtiposolicitud = idtiposolicitud;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

   @Column(name = "idusuario")
   public Integer getIdusuario()
   {
      return this.idusuario;
   }

   public void setIdusuario(Integer idusuario)
   {
      this.idusuario = idusuario;
   }

}
