package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subcategoria generated by hbm2java
 */
@Entity
@Table(name = "subcategoria"
      , catalog = "bdalmacen")
public class Subcategoria implements java.io.Serializable
{

   private Integer idsubcategoria;
   private String subcategoria;
   private String codigosubcategoria;
   private String descripcion;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idcategoria;
   private Integer idestado;

   public Subcategoria()
   {
   }

   public Subcategoria(String subcategoria, String codigosubcategoria, String descripcion, String fecharegistro, String fechamodificacion, Integer idcategoria, Integer idestado)
   {
      this.subcategoria = subcategoria;
      this.codigosubcategoria = codigosubcategoria;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idcategoria = idcategoria;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idsubcategoria", unique = true, nullable = false)
   public Integer getIdsubcategoria()
   {
      return this.idsubcategoria;
   }

   public void setIdsubcategoria(Integer idsubcategoria)
   {
      this.idsubcategoria = idsubcategoria;
   }

   @Column(name = "subcategoria", length = 50)
   public String getSubcategoria()
   {
      return this.subcategoria;
   }

   public void setSubcategoria(String subcategoria)
   {
      this.subcategoria = subcategoria;
   }

   @Column(name = "codigosubcategoria", length = 50)
   public String getCodigosubcategoria()
   {
      return this.codigosubcategoria;
   }

   public void setCodigosubcategoria(String codigosubcategoria)
   {
      this.codigosubcategoria = codigosubcategoria;
   }

   @Column(name = "descripcion", length = 250)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idcategoria")
   public Integer getIdcategoria()
   {
      return this.idcategoria;
   }

   public void setIdcategoria(Integer idcategoria)
   {
      this.idcategoria = idcategoria;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
