package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tiposolicitud generated by hbm2java
 */
@Entity
@Table(name = "tiposolicitud"
      , catalog = "bdalmacen")
public class Tiposolicitud implements java.io.Serializable
{

   private Integer idtiposolicitud;
   private String tiposolicitud;
   private String observacion;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idestado;

   public Tiposolicitud()
   {
   }

   public Tiposolicitud(String tiposolicitud)
   {
      this.tiposolicitud = tiposolicitud;
   }

   public Tiposolicitud(String tiposolicitud, String observacion, String fecharegistro, String fechamodificacion, Integer idestado)
   {
      this.tiposolicitud = tiposolicitud;
      this.observacion = observacion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idtiposolicitud", unique = true, nullable = false)
   public Integer getIdtiposolicitud()
   {
      return this.idtiposolicitud;
   }

   public void setIdtiposolicitud(Integer idtiposolicitud)
   {
      this.idtiposolicitud = idtiposolicitud;
   }

   @Column(name = "tiposolicitud", nullable = false, length = 50)
   public String getTiposolicitud()
   {
      return this.tiposolicitud;
   }

   public void setTiposolicitud(String tiposolicitud)
   {
      this.tiposolicitud = tiposolicitud;
   }

   @Column(name = "observacion", length = 250)
   public String getObservacion()
   {
      return this.observacion;
   }

   public void setObservacion(String observacion)
   {
      this.observacion = observacion;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
