package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Unidadmedida generated by hbm2java
 */
@Entity
@Table(name = "unidadmedida"
      , catalog = "bdalmacen")
public class Unidadmedida implements java.io.Serializable
{

   private Integer idunidadmedida;
   private String unidadmedida;
   private String sigla;
   private String descripcion;
   private String fecharegistro;
   private String fechamodificacion;
   private Integer idestado;

   public Unidadmedida()
   {
   }

   public Unidadmedida(String unidadmedida, String sigla, String descripcion)
   {
      this.unidadmedida = unidadmedida;
      this.sigla = sigla;
      this.descripcion = descripcion;
   }

   public Unidadmedida(String unidadmedida, String sigla, String descripcion, String fecharegistro, String fechamodificacion, Integer idestado)
   {
      this.unidadmedida = unidadmedida;
      this.sigla = sigla;
      this.descripcion = descripcion;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idunidadmedida", unique = true, nullable = false)
   public Integer getIdunidadmedida()
   {
      return this.idunidadmedida;
   }

   public void setIdunidadmedida(Integer idunidadmedida)
   {
      this.idunidadmedida = idunidadmedida;
   }

   @Column(name = "unidadmedida", nullable = false, length = 50)
   public String getUnidadmedida()
   {
      return this.unidadmedida;
   }

   public void setUnidadmedida(String unidadmedida)
   {
      this.unidadmedida = unidadmedida;
   }

   @Column(name = "sigla", nullable = false, length = 10)
   public String getSigla()
   {
      return this.sigla;
   }

   public void setSigla(String sigla)
   {
      this.sigla = sigla;
   }

   @Column(name = "descripcion", nullable = false, length = 250)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
