package org.almacen.model;

// Generated 08-may-2015 17:42:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario"
      , catalog = "bdalmacen")
public class Usuario implements java.io.Serializable
{

   private Integer idusuario;
   private String nombreusuario;
   private String password;
   private String fecharegistro;
   private String fechamodificacion;
   private String observacion;
   private Integer idpersona;
   private Integer idestado;

   public Usuario()
   {
   }

   public Usuario(String nombreusuario, String password)
   {
      this.nombreusuario = nombreusuario;
      this.password = password;
   }

   public Usuario(String nombreusuario, String password, String fecharegistro, String fechamodificacion, String observacion, Integer idpersona, Integer idestado)
   {
      this.nombreusuario = nombreusuario;
      this.password = password;
      this.fecharegistro = fecharegistro;
      this.fechamodificacion = fechamodificacion;
      this.observacion = observacion;
      this.idpersona = idpersona;
      this.idestado = idestado;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idusuario", unique = true, nullable = false)
   public Integer getIdusuario()
   {
      return this.idusuario;
   }

   public void setIdusuario(Integer idusuario)
   {
      this.idusuario = idusuario;
   }

   @Column(name = "nombreusuario", nullable = false, length = 50)
   public String getNombreusuario()
   {
      return this.nombreusuario;
   }

   public void setNombreusuario(String nombreusuario)
   {
      this.nombreusuario = nombreusuario;
   }

   @Column(name = "password", nullable = false, length = 50)
   public String getPassword()
   {
      return this.password;
   }

   public void setPassword(String password)
   {
      this.password = password;
   }

   @Column(name = "fecharegistro", length = 20)
   public String getFecharegistro()
   {
      return this.fecharegistro;
   }

   public void setFecharegistro(String fecharegistro)
   {
      this.fecharegistro = fecharegistro;
   }

   @Column(name = "fechamodificacion", length = 20)
   public String getFechamodificacion()
   {
      return this.fechamodificacion;
   }

   public void setFechamodificacion(String fechamodificacion)
   {
      this.fechamodificacion = fechamodificacion;
   }

   @Column(name = "observacion", length = 500)
   public String getObservacion()
   {
      return this.observacion;
   }

   public void setObservacion(String observacion)
   {
      this.observacion = observacion;
   }

   @Column(name = "idpersona")
   public Integer getIdpersona()
   {
      return this.idpersona;
   }

   public void setIdpersona(Integer idpersona)
   {
      this.idpersona = idpersona;
   }

   @Column(name = "idestado")
   public Integer getIdestado()
   {
      return this.idestado;
   }

   public void setIdestado(Integer idestado)
   {
      this.idestado = idestado;
   }

}
